### ISSUE TITLE
Docker image doesn't support leader-election flag

### ISSUE THREAD

**Issue by mcinquin** [timescale/prometheus-postgresql-adapter#62]
Hello,

Docker image doesn't support leader-election flag.

docker-compose.yml
```
version: '2.1'
services:
 prometheus_postgresql_adapter_1:
   image: timescale/prometheus-postgresql-adapter:master
   ports:
     - "9201:9201"
   command: "-pg.host=x.x.x.x -pg.prometheus-log-samples -leader-election.pg-advisory-lock-id=1 -leader-election.pg-advisory-lock.prometheus-timeout=6s"

 prometheus_postgresql_adapter_2:
   image: timescale/prometheus-postgresql-adapter:master
   ports:
     - "9202:9202"
   command: "-pg.host=x.x.x.x -pg.prometheus-log-samples -leader-election.pg-advisory-lock-id=1 -leader-election.pg-advisory-lock.prometheus-timeout=6s"
```

Logs:
```
...
prometheus_postgresql_adapter_1_1  | flag provided but not defined: -leader-election.pg-advisory-lock-id
...
prometheus_postgresql_adapter_2_1  | flag provided but not defined: -leader-election.pg-advisory-lock-id
...
```

Regards.

**Comment by mcinquin** [comment]
up

**Comment by niksajakovljevic** [comment]
Hi @Shini31 The example in readme was wrong and pointed to `:master` docker tag. Now it's fixed to be `:latest`. That should solve the problem.

Let me know if this fixes the problem for you?

**Comment by mcinquin** [comment]
The issue is still relevant with the `:latest` docker tag. The errors in the log file are the same.

**Comment by niksajakovljevic** [comment]
I think `command:` should receive a list of arguments. eg `["-pg.host","xxx", "-leader-election.pg-advisory-lock-id", "1"....]`

**Comment by mcinquin** [comment]
I forgot to change the docker image tag for my second adapter in my docker-compose file. All is good now ! Thanks.
